[package]
name = "lsh_search"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
ndarray = "0.15"
ndarray-linalg = { version = "0.16.0", features = ["intel-mkl-static"] }
rand = "0.8"
rand_distr = "0.4.0"
rayon = "1.5"
thiserror = "1.0"
bloom = "0.3.2"
ordered-float = "3.0"
